### ISSUE TITLE
Add Linux Support

### ISSUE THREAD

**Issue by timbrinded** [matter-labs/zkcli-block-explorer#12]
#### 📝 Description

Please add support for Linux. Currently the docker compose file references `http://host.docker.internal` which is a Docker Desktop only feature - i.e. Windows/Mac only.

#### 🤔 Rationale

The overwhelming majority of development is done on Linux, being able to use the CLI to spin up networks and working block explorers would be a boon to the ecosystem DevEx.

#### 🖼️ Mockups/Examples

Have multiple docker compose files, depending on the target, which can be selected based on host OS detected.

#### 📋 Additional Context

Add any other context or information about the feature request here.

**Comment by JackHamer09** [comment]
Hey! This PR should fix this issue https://github.com/matter-labs/zkcli-block-explorer/pull/9
And it should become available in latest version of `zksync-cli` soon
